### ISSUE TITLE
生一個讓 view 可以判斷使用者身份的實體變數

### ISSUE THREAD

**Issue by ItsBoyu** [codeboard-team/CodeBoard#42]
1. 未登入
2. 已登入-出題者
3. 已登入-非出題者 (解題者)

**Comment by eudora-hsj** [comment]
- [ ] show頁的card list 判斷出題者/解題者的 按鈕顯示切換
- [ ] 非出題者進入別人的board時編輯相關按鈕要隱藏
![image](https://user-images.githubusercontent.com/52728413/82227293-27ad5a00-995a-11ea-9f67-f38b1a6bfea7.png)
